### ISSUE TITLE
Fix for bootstrap.js to insert default users

### ISSUE THREAD

**Issue by bluepuma77** [DAB0mB/angular-meteor-whatsapp#1]
In `Meteor.startup()` new users are inserted, this leads to errors when starting a second time.

I think instead of `if (Chats.find().count() !== 0) return;` 
it should check `if (Meteor.users.find().count() !== 0) return;`
before inserting the same default users

**Comment by DAB0mB** [comment]
Fixed. See [reference](https://github.com/DAB0mB/angular-meteor-whatsapp/blob/master/server/bootstrap.js#L2)
