### ISSUE TITLE
Meteor, Angular, and Ionic WhatsApp tutorial issue step 3

### ISSUE THREAD

**Issue by souphan** [DAB0mB/angular-meteor-whatsapp#10]
I was going through the tutorial yesterday, and have noticed the new updates today that included ES6 classes.

I was on step 3 of the tutorial, but am now unable to access it.  I can get to everything else, but step 3.  
I get a blank screen when entering this URL into my browser:
 http://www.angular-meteor.com/tutorials/whatsapp/meteor/methods

The error I see when I inspect the console is this:
Uncaught Error: Multiple files in patch. Must specify filename which is one of: client/scripts/controllers/chat.controller.js, client/templates/chat.html

**Comment by souphan** [comment]
I will take look at the file in github =D.

**Comment by souphan** [comment]
I found the error message here in this diff.js file:
https://github.com/meteor/tutorial-tools/blob/master/tutorial-diff-box/diff-box.jsx

So right now this isn't true:
 if (! this.filename) {
      throw new Error(`Multiple files in patch. Must specify filename which is one of: ${filenames.join(", ")}`);
    }

Still looking around.  Sorry I'm a Meteor noob.

**Comment by DAB0mB** [comment]
Thank you for bringing this issue for my attention, apparently I missed it. I will be fixing it today.

**Comment by DAB0mB** [comment]
Here, it should be fixed now
