### ISSUE TITLE
How can i use Ionic Scss and Fonts using this Structure ?

### ISSUE THREAD

**Issue by Furqankhanzada** [DAB0mB/angular-meteor-whatsapp#14]
I am building an app using your tutorial and facing 2 minour issue about fonts and Scss.
see screenshot 
![screen shot 2016-04-30 at 9 49 28 pm](https://cloud.githubusercontent.com/assets/2400215/14937342/01b0f0fc-0f1e-11e6-9023-076364c4dd13.png)
 and second thing is how can i access ionic Scss ? let say i want to change fonts path using scss variable.

**Comment by DAB0mB** [comment]
Please look at this https://github.com/DAB0mB/angular-meteor-whatsapp/issues/12 issue
