### ISSUE TITLE
Bootstrapping steps in tutorial may need updating

### ISSUE THREAD

**Issue by ccuilla** [DAB0mB/angular-meteor-whatsapp#15]
It seems before doing:

```
meteor npm install ionic-scripts --save
```

You _may_ need to do the following:

```
meteor npm install angular-animate --save
meteor npm install angular-sanitize --save
meteor npm install angular-ui-router@^0.2.13 --save
```

Also though, I get this error when installing ionic-scripts:

```
npm WARN deprecated ionic-scripts@1.3.1: Wrong dependency

npm ERR! version not found: ionic-sdk@1.3.1
```

It looks like ionic-scripts declares a dependency on ionic-sdk version 1.3.1. But the latest version of ionic-sdk appears to be 1.2.4.

**Comment by DAB0mB** [comment]
Install version 0.0.2 instead, as for now version 1.3.1 is deprecated until `ionic-sdk@1.31` will be released.

**Comment by ccuilla** [comment]
Version 0.0.2 of ionic-scripts?

**Comment by DAB0mB** [comment]
@ccuilla I've just published a new release of `ionic-scripts`, can you please try it and tell me if it works?

**Comment by ccuilla** [comment]
I was able to at least install. I assume the rest will work from here on. But I won't be able to test that until later. Thanks!
