### ISSUE TITLE
Step 1.10 controllerAs section

### ISSUE THREAD

**Issue by obezuk** [DAB0mB/angular-meteor-whatsapp#16]
Hi,

Great tutorial, I'm new to Ionic and AngularJS development and found while using this tutorial the section regarding "controllerAs" syntax was not very clear.

While following the tutorial and creating the chats view I was unable to populate data in the view. 

I followed the hint:

> From now on we will use our controller as the view model using the controllerAs syntax, which basically means that instead of defining data models on the $scope we will define them on the controller itself using the this argument. For more information, see AngularJS's docs about ngController.

And added this to the ion-view and it worked.

`<ion-view view-title="Chats" ng-controller="ChatsCtrl as chats">`

Is this the correct way to use controllerAs with Meteor/Ionic/Angular? Should the examples in the tutorial and repository be updated to include this line?

Thanks,

Tim Obezuk

**Comment by obezuk** [comment]
I've progressed further and found the routes can also be updated to do this by adding:

`controller: 'ChatsCtrl as chats'`

I'm going to close this, hopefully this information can help others learn :)

**Comment by DaveStark** [comment]
Yeah that's true, I had the same problem,however, another solution could be, in the routes.js adding:
`controller: 'ChatsCtrl',
 controllerAs: 'chats'`
