### ISSUE TITLE
Does not build due to angular-templates package (mac)

### ISSUE THREAD

**Issue by saadgit** [DAB0mB/angular-meteor-whatsapp#20]
While trying to build the project, I got started coming with angular-template. 

>
saad@SE-C02KVEB9F6T6:~/Development/git/angular-meteor-whatsapp$ meteor
[[[[[ ~/Development/git/angular-meteor-whatsapp ]]]]]                              

>=> Started proxy.                             
=> Started MongoDB.                           
                                              
>=> Meteor 1.3.4: npm@3.9.6, .babelrc support, improved import declarations,
DDP update batching, and more: https://github.com/meteor/meteor/blob/master/History.md#v134

>This release is being downloaded in the background. Update your app to
Meteor 1.3.4 by running 'meteor update'.
                                              
                                                                                   
>Unable to resolve some modules:

>  "angular-animate" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "angular-meteor" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "angular-meteor-auth" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "angular-moment" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "angular-sanitize" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
> "angular-ui-router" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "ionic-scripts" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/controllers/chat.controller.js
(web.browser)
>  "angular" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js (web.browser)
>  "angular-ecmascript/module-loader" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/lib/app.js
(web.browser)
>  "angular-ecmascript/module-helpers" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/routes.js
(web.browser)
>  "moment" in /Users/saad/Development/git/angular-meteor-whatsapp/client/scripts/filters/calendar.filter.js (web.browser)
                                              
>Consider running: meteor npm install --save angular-animate angular-meteor angular-meteor-auth angular-moment
angular-sanitize angular-ui-router ionic-scripts angular angular-ecmascript moment
                                              
>=> Started your app.                          

>=> App running at: http://localhost:3000/

It seems like angular-templates (https://atmospherejs.com/meteor/angular-templates) package is already Flagged which seems to be the bottleneck for running this app.

Tried to update the packages but no fix,

>saad@SE-C02KVEB9F6T6:~/Development/git/angular-meteor-whatsapp$ meteor update
                                              
>Changes to your project's package version selections from updating the release:
                                              
>accounts-base          upgraded from 1.2.4 to 1.2.8
allow-deny             upgraded from 1.0.2 to 1.0.5
autoupdate             upgraded from 1.2.6 to 1.2.10
babel-compiler         upgraded from 6.5.2 to 6.8.3
babel-runtime          upgraded from 0.1.6 to 0.1.9_1
base64                 upgraded from 1.0.6 to 1.0.9
binary-heap            upgraded from 1.0.6 to 1.0.9
blaze                  upgraded from 2.1.5 to 2.1.8
blaze-tools            upgraded from 1.0.6 to 1.0.9
boilerplate-generator  upgraded from 1.0.6 to 1.0.9
caching-compiler       upgraded from 1.0.2 to 1.0.5_1
caching-html-compiler  upgraded from 1.0.4 to 1.0.6
callback-hook          upgraded from 1.0.6 to 1.0.9
check                  upgraded from 1.1.2 to 1.2.3
ddp                    upgraded from 1.2.3 to 1.2.5
ddp-client             upgraded from 1.2.3 to 1.2.8_1
ddp-common             upgraded from 1.2.3 to 1.2.6
ddp-rate-limiter       upgraded from 1.0.2 to 1.0.5
ddp-server             upgraded from 1.2.4 to 1.2.8_1
deps                   upgraded from 1.0.10 to 1.0.12
diff-sequence          upgraded from 1.0.3 to 1.0.6
ecmascript             upgraded from 0.4.1 to 0.4.6_1
ecmascript-runtime     upgraded from 0.2.8 to 0.2.11_1
ejson                  upgraded from 1.0.9 to 1.0.12
email                  upgraded from 1.0.10 to 1.0.14_1
es5-shim               upgraded from 4.5.8 to 4.5.12_1
fastclick              upgraded from 1.0.9 to 1.0.12
geojson-utils          upgraded from 1.0.6 to 1.0.9
hot-code-push          upgraded from 1.0.2 to 1.0.4
html-tools             upgraded from 1.0.7 to 1.0.10
htmljs                 upgraded from 1.0.7 to 1.0.10
http                   upgraded from 1.1.3 to 1.1.7
id-map                 upgraded from 1.0.5 to 1.0.8
jquery                 upgraded from 1.11.6 to 1.11.9
launch-screen          upgraded from 1.0.8 to 1.0.12
less                   upgraded from 2.5.6 to 2.6.3_1
livedata               upgraded from 1.0.16 to 1.0.18
localstorage           upgraded from 1.0.7 to 1.0.11
logging                upgraded from 1.0.10 to 1.0.13_1
meteor                 upgraded from 1.1.12 to 1.1.15_1
meteor-base            upgraded from 1.0.2 to 1.0.4
minifier-css           upgraded from 1.1.9 to 1.1.12_1
minifier-js            upgraded from 1.1.9 to 1.1.12_1
minimongo              upgraded from 1.0.12 to 1.0.17
mobile-experience      upgraded from 1.0.2 to 1.0.4
mobile-status-bar      upgraded from 1.0.10 to 1.0.12
modules                upgraded from 0.5.1 to 0.6.4
modules-runtime        upgraded from 0.6.1 to 0.6.4_1
mongo                  upgraded from 1.1.5 to 1.1.9_1
mongo-id               upgraded from 1.0.2 to 1.0.5
npm-mongo              upgraded from 1.4.41 to 1.4.44_1
observe-sequence       upgraded from 1.0.9 to 1.0.12
ordered-dict           upgraded from 1.0.5 to 1.0.8
promise                upgraded from 0.6.5 to 0.7.2_1
random                 upgraded from 1.0.7 to 1.0.10
rate-limit             upgraded from 1.0.2 to 1.0.5
reactive-dict          upgraded from 1.1.5 to 1.1.8
reactive-var           upgraded from 1.0.7 to 1.0.10
reload                 upgraded from 1.1.6 to 1.1.10
retry                  upgraded from 1.0.5 to 1.0.8
routepolicy            upgraded from 1.0.8 to 1.0.11
service-configuration  upgraded from 1.0.7 to 1.0.10
session                upgraded from 1.1.3 to 1.1.6
sha                    upgraded from 1.0.5 to 1.0.8
spacebars              upgraded from 1.0.9 to 1.0.12
spacebars-compiler     upgraded from 1.0.9 to 1.0.12
srp                    upgraded from 1.0.6 to 1.0.9
standard-minifier-css  upgraded from 1.0.4 to 1.0.7_1
standard-minifier-js   upgraded from 1.0.4 to 1.0.7_1
templating             upgraded from 1.1.7 to 1.1.12_1
templating-tools       upgraded from 1.0.2 to 1.0.4
tracker                upgraded from 1.0.11 to 1.0.14
ui                     upgraded from 1.0.9 to 1.0.11
underscore             upgraded from 1.0.6 to 1.0.9
url                    upgraded from 1.0.7 to 1.0.10
webapp                 upgraded from 1.2.6 to 1.2.9_1
webapp-hashing         upgraded from 1.0.7 to 1.0.9

>angular-meteor-whatsapp: updated to Meteor 1.3.4.1.
=> Errors while upgrading packages:           
                                              
>While checking for angular-templates@1.0.4:
>error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
platform.

Is there any other work around?

**Comment by DAB0mB** [comment]
This might be related to the following issue https://github.com/Urigo/angular-meteor/issues/1391.
Can you please downgrade `meteor` and see if it works?

**Comment by DAB0mB** [comment]
I'm closing this issue due to unresponsiveness
