### ISSUE TITLE
Error: [angular-meteor][err][404] client/templates/tabs.html - HTML template does not exists! You can disable this error by following this guide

### ISSUE THREAD

**Issue by paixaop** [DAB0mB/angular-meteor-whatsapp#21]
Angular cannot find any of the templates when built with meteor 1.3.4.4.
Did a git clone of the repository app was working, then upgraded to 1.3.4.4 and now I get template not found messages in the browser's console.

How can i fix this error?

**Comment by gabehopper** [comment]
I'm getting the same issue on Meteor 1.3.4.4

**Comment by tparkin** [comment]
+1 Same issue on Meteor 1.3.4.4

**Comment by bmanturner** [comment]
I believe this may be related: https://github.com/Urigo/angular-meteor/issues/1391

**Comment by DAB0mB** [comment]
`angular-meteor`'s team is working on a fix according to https://github.com/Urigo/angular-meteor/issues/1391
