### ISSUE TITLE
Step 2.5 'this.data.remove is not a function'

### ISSUE THREAD

**Issue by abtx** [DAB0mB/angular-meteor-whatsapp#27]
I get this error in step 2.5.

**Comment by abtx** [comment]
I keep getting this error. Can I point out that the tutorial asks to use `this.data.remove(chat)` and the commit uses `his.data.remove(chat._id)`? I'm not sure why I'm getting the error though, I've got the routes set up to use the correct controller, the Mongo initialisation is in place, and server side code is just as in the example.

**Comment by blitzmann** [comment]
I second this, this seems to be broken
