### ISSUE TITLE
this.$ionicLoading throws error

### ISSUE THREAD

**Issue by robertclarkson** [DAB0mB/angular-meteor-whatsapp#29]
http://www.angular-meteor.com/tutorials/whatsapp/meteor/userprofile

this.$ionicLoading

should be

this.$ionicPopup

i think

**Comment by robertclarkson** [comment]
Ah no maybe better if the bottom line is

ProfileCtrl.$inject = ['$state', '$ionicPopup', '$ionicLoading', '$log'];

with '$ionicLoading' added

**Comment by DAB0mB** [comment]
@robertclarkson Can you please provide more details? Which step does the error occur? What kind of error message do you receive?
